openapi: 3.1.0
info:
  title: Clemson GPT News API
  description: Retrieve summarized news articles from Clemson University college websites.
  version: 1.0.0
  x-logo:
    url: https://cuheadlines.onrender.com/static/logo.svg
    altText: Clemson Tiger Paw
  x-openapi-spec: https://cuheadlines.onrender.com/openapi.json
servers:
  - url: https://cuheadlines.onrender.com
    description: Production server
paths:
  /latest-news:
    get:
      operationId: getLatestNews
      summary: Get summarized news from Clemson University colleges
      description: Retrieve and summarize the latest news articles from a specific Clemson University college website.
      parameters:
        - name: college
          in: query
          description: The name of the Clemson college to get news from (e.g., "College of Science", "College of Engineering")
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A successful response containing summarized news articles
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad request, such as missing or invalid college name
        "500":
          description: Server error or failure to retrieve articles
components:
  schemas: {}
